language: r
r:
  - 3.5
  - 3.6
  - release
  - devel
env:
  global:
    - R_LIBS_USER=~/R
install:
  - R --version
  - R -e '.libPaths(); sessionInfo()'
#  CRAN packages required by RPANDA
  - grep ^Imports DESCRIPTION | sed -e 's/Imports. //' -e 's/,/ /g' -e 's/$//' | xargs Rscript -e  'install.packages(append(commandArgs(TRUE), "picante"), dep = TRUE, repos = c("http://cran.rstudio.com", "http://cran.r-project.org"))'
#  CRAN packages required by RPANDA tests
  - Rscript -e 'install.packages(c("testthat", "vegan", "permute", "lattice", "nlme"), dep = TRUE, repos = c("http://cran.rstudio.com", "http://cran.r-project.org"))'
script:
  - R CMD build --no-manual .
  - R CMD INSTALL *gz
  - cd tests && Rscript -e 'library(methods);library(testthat);library(RPANDA); test_check("RPANDA")'

